[client]
showSidebarNavigation = false
 
[server]
headless = true
 
[browser]
gatherUsageStats = false
 
[theme]
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f8fa"
textColor = "#111827"
font = "sans serif"
 
